version: '3.8'

services:
  raw-fusion-training:
    build:
      context: .
      dockerfile: Dockerfile
    image: raw-fusion-diffusion:latest
    container_name: raw_fusion_training
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0,1,2,3
    volumes:
      - ./data:/workspace/data
      - ./checkpoints:/workspace/checkpoints
      - ./logs:/workspace/logs
      - ./outputs:/workspace/outputs
    shm_size: '16gb'
    stdin_open: true
    tty: true
    command: python -m training.train_diffusion --config configs/training_config.yaml
    
  tensorboard:
    image: tensorflow/tensorflow:latest
    container_name: raw_fusion_tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/logs
    command: tensorboard --logdir=/logs --host=0.0.0.0
    
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raw_fusion_jupyter
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
