# Render.com Deployment Configuration

# Web Service Configuration
services:
  - type: web
    name: raw-diffusion-api
    env: python
    region: oregon
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.serve:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MODEL_PATH
        value: /opt/render/project/models
      - key: TORCH_HOME
        value: /opt/render/project/.torch
    disk:
      name: model-storage
      mountPath: /opt/render/project/models
      sizeGB: 20

  # Background Worker for Training
  - type: worker
    name: raw-diffusion-trainer
    env: python
    region: oregon
    plan: pro-plus  # GPU instance
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scripts/train_orchestrator.py --data_dir /opt/render/project/data --output_dir /opt/render/project/outputs"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: CUDA_VISIBLE_DEVICES
        value: 0
    disk:
      name: training-data
      mountPath: /opt/render/project/data
      sizeGB: 100
